language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26

install: ./gradlew clean assemble assembleAndroidTest --stacktrace

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle